-- 商品マスタテーブル
CREATE TABLE items (
    PRD_ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE CHAR(13) UNIQUE NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRICE INT NOT NULL
);

-- 取引テーブル
CREATE TABLE transactions (
    TRD_ID INT AUTO_INCREMENT PRIMARY KEY,
    DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EMP_CD CHAR(10) DEFAULT '9999999999',
    STORE_CD CHAR(5) DEFAULT '30',
    POS_NO CHAR(3) DEFAULT '90',
    TOTAL_AMT INT DEFAULT 0
);

-- 取引明細テーブル（複合主キー）
CREATE TABLE transaction_items (
    TRD_ID INT,
    DTL_ID INT,
    PRD_ID INT,
    PRD_CODE CHAR(13),
    PRD_NAME VARCHAR(50),
    PRD_PRICE INT,
    PRIMARY KEY (TRD_ID, DTL_ID),
    FOREIGN KEY (TRD_ID) REFERENCES transactions(TRD_ID),
    FOREIGN KEY (PRD_ID) REFERENCES items(PRD_ID)
);
